const tools = [
  // ai_and_llm
  { id: 'chatgpt', name: 'ChatGPT', desc: 'AI-assisted analysis & OSINT reasoning', url: 'https://chat.openai.com/', category: 'ai_and_llm' },
  { id: 'gemini', name: 'Google Gemini', desc: 'Google\'s multimodal AI', url: 'https://gemini.google.com/', category: 'ai_and_llm' },
  { id: 'grok', name: 'Grok (xAI)', desc: 'Real-time AI search from X', url: 'https://grok.x.ai/', category: 'ai_and_llm' },
  { id: 'duckai', name: 'DuckDuckGo AI', desc: 'Private AI chat', url: 'https://duckduckgo.com/chat', category: 'ai_and_llm' },
  { id: 'pentestergpt', name: 'PentesterGPT', desc: 'GPT for penetration testing', url: 'https://github.com/GreyDGL/PentesterGPT', category: 'ai_and_llm' },
  { id: 'dorkgenius', name: 'DorkGenius', desc: 'AI tool for generating custom search queries', url: 'https://dorkgenius.com/', category: 'ai_and_llm' },
  { id: 'dorkgpt', name: 'DorkGPT', desc: 'Generate Google Dorks with AI', url: 'https://www.dorkgpt.com/', category: 'ai_and_llm' },
  { id: 'huggingface', name: 'Hugging Face', desc: 'AI models & datasets', url: 'https://huggingface.co/', category: 'ai_and_llm' },
  { id: 'linkurious', name: 'Linkurious', desc: 'Platform for graph analysis', url: 'https://linkurious.com', category: 'ai_and_llm' },
  { id: 'opencti', name: 'OpenCTI', desc: 'Threat intelligence platform', url: 'https://github.com/OpenCTI-Platform/opencti', category: 'ai_and_llm' },
  { id: 'perplexity-ai', name: 'Perplexity AI', desc: 'AI-powered web search', url: 'https://www.perplexity.ai/', category: 'ai_and_llm' },
  { id: 'phind', name: 'Phind', desc: 'AI search for developers', url: 'https://www.phind.com', category: 'ai_and_llm' },

  // archives
  { id: 'archive-today', name: 'archive.today', desc: 'Save / view snapshots', url: 'https://archive.today/', category: 'archives' },
  { id: 'internet-archive', name: 'Internet Archive', desc: 'Archive.org', url: 'https://archive.org/', category: 'archives' },
  { id: 'wayback-machine', name: 'Wayback Machine', desc: 'Archived webpages', url: 'https://web.archive.org/', category: 'archives' },

  // automation_and_frameworks
  { id: 'buscador', name: 'Buscador', desc: 'OSINT virtual machine for Kali Linux', url: 'https://github.com/IntelTechniques/Buscador', category: 'automation_and_frameworks' },
  { id: 'maltego', name: 'Maltego', desc: 'Graph-based link analysis', url: 'https://www.maltego.com/', category: 'automation_and_frameworks' },
  { id: 'osint-framework', name: 'OSINT Framework', desc: 'OSINT tool map', url: 'https://osintframework.com/', category: 'automation_and_frameworks' },
  { id: 'recon-ng', name: 'Recon-ng', desc: 'Web reconnaissance framework', url: 'https://github.com/lanmaster53/recon-ng', category: 'automation_and_frameworks' },
  { id: 'spiderfoot', name: 'SpiderFoot', desc: 'Automated OSINT scanner', url: 'https://github.com/smicallef/spiderfoot', category: 'automation_and_frameworks' },
  { id: 'theharvester', name: 'theHarvester', desc: 'OSINT email/host discovery', url: 'https://github.com/laramies/theHarvester', category: 'automation_and_frameworks' },

  // browsers
  { id: 'atom', name: 'Atom', desc: 'Russian web browser', url: 'https://browser.ru/', category: 'browsers' },
  { id: 'brave', name: 'Brave', desc: 'Privacy-focused browser', url: 'https://brave.com', category: 'browsers' },
  { id: 'bromite', name: 'Bromite', desc: 'Chromium fork with ad blocking', url: 'https://www.bromite.org/', category: 'browsers' },
  { id: 'centbrowser', name: 'CentBrowser', desc: 'Customized Chromium browser', url: 'http://www.centbrowser.com', category: 'browsers' },
  { id: 'chrome', name: 'Chrome', desc: 'Google\'s web browser', url: 'https://www.google.com/chrome', category: 'browsers' },
  { id: 'comodo-dragon', name: 'Comodo Dragon', desc: 'Secure web browser', url: 'https://www.comodo.com/home/browsers-toolbars/browser.php', category: 'browsers' },
  { id: 'coowon', name: 'Coowon', desc: 'Gaming-oriented browser', url: 'http://coowon.com', category: 'browsers' },
  { id: 'edge', name: 'Edge', desc: 'Microsoft\'s web browser', url: 'https://www.microsoft.com/en-us/windows/microsoft-edge/microsoft-edge', category: 'browsers' },
  { id: 'firefox', name: 'Firefox', desc: 'Mozilla\'s web browser', url: 'https://www.mozilla.org', category: 'browsers' },
  { id: 'gnu-icecat', name: 'Gnu Icecat', desc: 'Free software browser', url: 'https://icecatbrowser.org/', category: 'browsers' },
  { id: 'librewolf', name: 'LibreWolf', desc: 'Privacy-focused Firefox fork', url: 'https://librewolf.net', category: 'browsers' },
  { id: 'maxthon', name: 'Maxthon', desc: 'Cloud-based browser', url: 'http://www.maxthon.com', category: 'browsers' },
  { id: 'mullvad-browser', name: 'Mullvad Browser', desc: 'Privacy-focused browser with Tor', url: 'https://mullvad.net/en/browser', category: 'browsers' },
  { id: 'opera', name: 'Opera', desc: 'Feature-rich web browser', url: 'http://www.opera.com', category: 'browsers' },
  { id: 'safari', name: 'Safari', desc: 'Apple\'s web browser', url: 'http://www.apple.com/safari', category: 'browsers' },
  { id: 'sleipnir', name: 'Sleipnir', desc: 'Customizable browser', url: 'http://www.fenrir-inc.com/jp/sleipnir', category: 'browsers' },
  { id: 'slimjet', name: 'Slimjet', desc: 'Fast web browser', url: 'http://www.slimjet.com', category: 'browsers' },
  { id: 'srware-iron', name: 'SRWare Iron', desc: 'Privacy-enhanced Chromium', url: 'http://www.srware.net/en/software_srware_iron.php', category: 'browsers' },
  { id: 'tor-browser', name: 'Tor Browser', desc: 'Anonymous browsing', url: 'https://www.torproject.org/projects/torbrowser.html.en', category: 'browsers' },
  { id: 'torch', name: 'Torch', desc: 'Media-focused browser', url: 'http://www.torchbrowser.com', category: 'browsers' },
  { id: 'ucbrowser', name: 'UCBrowser', desc: 'Mobile-focused browser', url: 'http://www.ucweb.com', category: 'browsers' },
  { id: 'vivaldi', name: 'Vivaldi', desc: 'Powerful personal browser', url: 'https://vivaldi.com', category: 'browsers' },
  { id: 'waterfox', name: 'Waterfox', desc: 'Fast private browser', url: 'https://www.waterfox.net/', category: 'browsers' },
  { id: 'yandex-browser', name: 'Yandex Browser', desc: 'Russian web browser', url: 'https://browser.yandex.com/desktop/main', category: 'browsers' },

  // business_intelligence
  { id: 'clearbit', name: 'Clearbit', desc: 'Company / person lookup', url: 'https://clearbit.com/', category: 'business_intelligence' },
  { id: 'crunchbase', name: 'Crunchbase', desc: 'Company intelligence', url: 'https://www.crunchbase.com/', category: 'business_intelligence' },
  { id: 'fullcontact', name: 'FullContact', desc: 'Contact enrichment', url: 'https://www.fullcontact.com/', category: 'business_intelligence' },
  { id: 'occrp-aleph', name: 'OCCRP Aleph', desc: 'Investigative data platform', url: 'https://aleph.occrp.org/', category: 'business_intelligence' },
  { id: 'opencorporates', name: 'OpenCorporates', desc: 'Company data', url: 'https://opencorporates.com/', category: 'business_intelligence' },
  { id: 'whoisxml', name: 'WhoisXML API', desc: 'WHOIS and domain data', url: 'https://whoisxmlapi.com/', category: 'business_intelligence' },
  { id: 'zoominfo', name: 'ZoomInfo', desc: 'Business intelligence', url: 'https://www.zoominfo.com/', category: 'business_intelligence' },

  // cloud_and_saas_osint
  { id: 'cloudenum', name: 'CloudEnum', desc: 'Multi-cloud OSINT enumeration', url: 'https://github.com/initstring/cloud_enum', category: 'cloud_and_saas_osint' },
  { id: 'grayhat-warfare', name: 'Grayhat Warfare', desc: 'Public cloud bucket search', url: 'https://buckets.grayhatwarfare.com', category: 'cloud_and_saas_osint' },

  // code_and_developer_intelligence
  { id: 'github-search', name: 'GitHub Search', desc: 'Code & repo search', url: 'https://github.com/', category: 'code_and_developer_intelligence' },
  { id: 'gitleaks', name: 'Gitleaks', desc: 'Scan for secrets in code', url: 'https://github.com/gitleaks/gitleaks', category: 'code_and_developer_intelligence' },
  { id: 'gitgrep', name: 'grep.app', desc: 'Code search', url: 'https://grep.app/', category: 'code_and_developer_intelligence' },
  { id: 'nerdydata', name: 'NerdyData', desc: 'Code and data search', url: 'https://www.nerdydata.com/', category: 'code_and_developer_intelligence' },
  { id: 'publicwww', name: 'PublicWWW', desc: 'Find sites using code/snippets', url: 'https://publicwww.com/', category: 'code_and_developer_intelligence' },
  { id: 'searchcode', name: 'SearchCode', desc: 'Code search', url: 'https://searchcode.com/', category: 'code_and_developer_intelligence' },
  { id: 'sourcegraph', name: 'SourceGraph', desc: 'Code search across repos', url: 'https://sourcegraph.com/', category: 'code_and_developer_intelligence' },
  { id: 'trufflehog', name: 'TruffleHog', desc: 'Find leaked credentials', url: 'https://github.com/trufflesecurity/trufflehog', category: 'code_and_developer_intelligence' },

  // crypto_intelligence
  { id: 'blockchair', name: 'Blockchair', desc: 'Blockchain explorer', url: 'https://blockchair.com/', category: 'crypto_intelligence' },
  { id: 'blockcypher', name: 'BlockCypher', desc: 'Blockchain web services', url: 'https://www.blockcypher.com/', category: 'crypto_intelligence' },
  { id: 'etherscan', name: 'Etherscan', desc: 'Ethereum transaction intelligence', url: 'https://etherscan.io/', category: 'crypto_intelligence' },
  { id: 'walletexplorer', name: 'WalletExplorer', desc: 'Bitcoin wallet clustering', url: 'https://www.walletexplorer.com/', category: 'crypto_intelligence' },

  // dark_web_intelligence
  { id: 'ahmia', name: 'Ahmia', desc: 'Dark web search engine', url: 'https://ahmia.fi', category: 'dark_web_intelligence' },
  { id: 'darksearch', name: 'DarkSearch', desc: 'Search dark web', url: 'https://darksearch.io/', category: 'dark_web_intelligence' },
  { id: 'dehashed', name: 'DeHashed', desc: 'Leaked credentials & data', url: 'https://www.dehashed.com/', category: 'dark_web_intelligence' },
  { id: 'onionscan', name: 'OnionScan', desc: 'Dark web site scanner', url: 'https://github.com/s-rah/onionscan', category: 'dark_web_intelligence' },
  { id: 'snusbase', name: 'Snusbase', desc: 'Leak & breach intelligence', url: 'https://snusbase.com/', category: 'dark_web_intelligence' },
  { id: 'torch-onion', name: 'Torch', desc: 'Tor search engine', url: 'http://torchdeedp3i2jigzejdmqjs3s3jd25tcjankofwmjicyqor4xglb3yd.onion/', category: 'dark_web_intelligence' },

  // data_breach_search_engines
  { id: 'credenshow', name: 'CredenShow', desc: 'Identify compromised credentials', url: 'https://credenshow.com/', category: 'data_breach_search_engines' },
  { id: 'have-i-been-pwned-breach', name: 'Have I Been Pwned', desc: 'Breach check', url: 'https://haveibeenpwned.com/', category: 'data_breach_search_engines' },
  { id: 'hib-ransomed', name: 'HIB Ransomed', desc: 'Check if data leaked in ransoms', url: 'https://haveibeenransom.com/', category: 'data_breach_search_engines' },
  { id: 'heroic-now', name: 'HEROIC.NOW', desc: 'Dark web leak scanner', url: 'https://heroic.com/', category: 'data_breach_search_engines' },
  { id: 'iknowyour-dad', name: 'IKnowYour.Dad', desc: 'Data breach search', url: 'https://iknowyour.dad/', category: 'data_breach_search_engines' },
  { id: 'stealseek', name: 'StealSeek', desc: 'Analyze data breaches', url: 'https://stealseek.io/', category: 'data_breach_search_engines' },
  { id: 'venacus', name: 'Venacus', desc: 'Data breach notifications', url: 'https://venacus.com/', category: 'data_breach_search_engines' },

  // domain_and_ip_intelligence
  { id: 'abuseipdb', name: 'AbuseIPDB', desc: 'Abuse reports for IPs', url: 'https://www.abuseipdb.com/', category: 'domain_and_ip_intelligence' },
  { id: 'builtwith', name: 'BuiltWith', desc: 'Web technology profiler', url: 'https://builtwith.com/', category: 'domain_and_ip_intelligence' },
  { id: 'censys-domain', name: 'Censys', desc: 'Internet-wide search', url: 'https://censys.io', category: 'domain_and_ip_intelligence' },
  { id: 'cisco-talos', name: 'Cisco Talos', desc: 'Reputation center', url: 'https://talosintelligence.com/', category: 'domain_and_ip_intelligence' },
  { id: 'dnsdumpster', name: 'DNSDumpster', desc: 'DNS reconnaissance', url: 'https://dnsdumpster.com/', category: 'domain_and_ip_intelligence' },
  { id: 'dnslytics', name: 'DNSlytics', desc: 'DNS & WHOIS lookup', url: 'https://www.dnslytics.com/', category: 'domain_and_ip_intelligence' },
  { id: 'ipinfo', name: 'IPinfo', desc: 'IP geolocation & data', url: 'https://ipinfo.io/', category: 'domain_and_ip_intelligence' },
  { id: 'mxtoolbox', name: 'MxToolbox', desc: 'DNS and blacklist checks', url: 'https://mxtoolbox.com/', category: 'domain_and_ip_intelligence' },
  { id: 'securitytrails', name: 'SecurityTrails', desc: 'Domain & DNS history', url: 'https://securitytrails.com/', category: 'domain_and_ip_intelligence' },
  { id: 'shodan-domain', name: 'Shodan', desc: 'Host search', url: 'https://www.shodan.io/', category: 'domain_and_ip_intelligence' },
  { id: 'ssllabs', name: 'SSL Labs', desc: 'SSL/TLS assessment', url: 'https://www.ssllabs.com/ssltest/', category: 'domain_and_ip_intelligence' },
  { id: 'viewdns', name: 'ViewDNS', desc: 'DNS tools', url: 'https://viewdns.info/', category: 'domain_and_ip_intelligence' },
  { id: 'whois-domaintools', name: 'Whois / DomainTools', desc: 'Domain registration', url: 'https://whois.domaintools.com/', category: 'domain_and_ip_intelligence' },

  // email_intelligence
  { id: 'emailrep', name: 'EmailRep', desc: 'Email reputation & risk', url: 'https://emailrep.io/', category: 'email_intelligence' },
  { id: 'epieos', name: 'Epieos', desc: 'Email & Phone reverse lookup', url: 'https://epieos.com/', category: 'email_intelligence' },
  { id: 'have-i-been-pwned-email', name: 'Have I Been Pwned', desc: 'Breach check', url: 'https://haveibeenpwned.com/', category: 'email_intelligence' },
  { id: 'holehe', name: 'Holehe', desc: 'Check if email is used on sites', url: 'https://github.com/megadose/holehe', category: 'email_intelligence' },
  { id: 'hunter-io', name: 'Hunter.io', desc: 'Email discovery', url: 'https://hunter.io/', category: 'email_intelligence' },
  { id: 'skymem', name: 'Skymem', desc: 'Email search engine', url: 'http://www.skymem.info/', category: 'email_intelligence' },
  { id: 'voilanorbert', name: 'VoilaNorbert', desc: 'Email finder', url: 'https://www.voilanorbert.com/', category: 'email_intelligence' },

  // geospatial_intelligence
  { id: 'google-earth', name: 'Google Earth', desc: 'Satellite imagery viewer', url: 'https://earth.google.com', category: 'geospatial_intelligence' },
  { id: 'suncalc', name: 'SunCalc', desc: 'Sun position calculator', url: 'https://www.suncalc.org', category: 'geospatial_intelligence' },
  { id: 'wigle', name: 'WiGLE', desc: 'Wireless network mapping', url: 'https://wigle.net/', category: 'geospatial_intelligence' },

  // image_and_video_osint
  { id: 'exiftool', name: 'ExifTool', desc: 'Read/write file metadata', url: 'https://github.com/exiftool/exiftool', category: 'image_and_video_osint' },
  { id: 'exifviewer', name: 'Exif Viewer', desc: 'Image metadata', url: 'https://exif-viewer.com/', category: 'image_and_video_osint' },
  { id: 'foto-forensics', name: 'FotoForensics', desc: 'Image forensics tool', url: 'https://fotoforensics.com/', category: 'image_and_video_osint' },
  { id: 'google-reverse-image', name: 'Google Reverse Image', desc: 'Reverse image search', url: 'https://images.google.com', category: 'image_and_video_osint' },
  { id: 'imgur-search', name: 'Imgur Search', desc: 'Imgur image search', url: 'https://imgur.com/', category: 'image_and_video_osint' },
  { id: 'invid-verification', name: 'InVID Verification', desc: 'Video verification tool', url: 'https://www.invid-project.eu/verification/', category: 'image_and_video_osint' },
  { id: 'pimeyes', name: 'PimEyes', desc: 'Face recognition search', url: 'https://pimeyes.com/', category: 'image_and_video_osint' },
  { id: 'tineye', name: 'TinEye', desc: 'Reverse image search', url: 'https://tineye.com/', category: 'image_and_video_osint' },
  { id: 'yandex-images', name: 'Yandex Images', desc: 'Reverse image search', url: 'https://yandex.com/images', category: 'image_and_video_osint' },

  // infographics_and_data_visualization
  { id: 'aeon', name: 'Aeon', desc: 'Timeline tool', url: 'http://www.aeontimeline.com', category: 'infographics_and_data_visualization' },
  { id: 'arbor-js', name: 'Arbor.js', desc: 'Graph visualization library', url: 'http://arborjs.org', category: 'infographics_and_data_visualization' },
  { id: 'beaker', name: 'Beaker', desc: 'Notebook for data exploration', url: 'http://beakernotebook.com', category: 'infographics_and_data_visualization' },
  { id: 'befunky', name: 'BeFunky', desc: 'Photo editor and infographic maker', url: 'https://www.befunky.com', category: 'infographics_and_data_visualization' },
  { id: 'bizint', name: 'BizInt', desc: 'Business intelligence visualization', url: 'http://www.bizint.com', category: 'infographics_and_data_visualization' },
  { id: 'cacoo', name: 'Cacoo', desc: 'Online diagramming', url: 'https://cacoo.com', category: 'infographics_and_data_visualization' },
  { id: 'canva', name: 'Canva', desc: 'Graphic design platform', url: 'https://www.canva.com', category: 'infographics_and_data_visualization' },
  { id: 'chart-js', name: 'Chart.js', desc: 'JavaScript charting library', url: 'http://www.chartjs.org', category: 'infographics_and_data_visualization' },
  { id: 'chartblocks', name: 'Chartblocks', desc: 'Online chart builder', url: 'http://www.chartblocks.com', category: 'infographics_and_data_visualization' },
  { id: 'circos', name: 'Circos', desc: 'Circular visualization tool', url: 'http://circos.ca', category: 'infographics_and_data_visualization' },
  { id: 'creately', name: 'Creately', desc: 'Diagramming tool', url: 'http://creately.com', category: 'infographics_and_data_visualization' },
  { id: 'crossfilter', name: 'Crossfilter', desc: 'Multidimensional data analysis', url: 'http://square.github.io/crossfilter', category: 'infographics_and_data_visualization' },
  { id: 'csvkit', name: 'csvkit', desc: 'CSV processing tools', url: 'https://github.com/wireservice/csvkit', category: 'infographics_and_data_visualization' },
  { id: 'd3js', name: 'D3js', desc: 'Data-driven documents library', url: 'https://d3js.org', category: 'infographics_and_data_visualization' },
  { id: 'data-visualization-catalogue', name: 'Data Visualization Catalogue', desc: 'Visualization methods reference', url: 'http://datavizcatalogue.com', category: 'infographics_and_data_visualization' },
  { id: 'datawrapper', name: 'Datawrapper', desc: 'Chart creation tool', url: 'https://datawrapper.de', category: 'infographics_and_data_visualization' },
  { id: 'dropmark', name: 'Dropmark', desc: 'Visual collaboration', url: 'http://www.dropmark.com', category: 'infographics_and_data_visualization' },
  { id: 'dygraphs', name: 'dygraphs', desc: 'Interactive charts', url: 'http://dygraphs.com', category: 'infographics_and_data_visualization' },
  { id: 'easely', name: 'Easely', desc: 'Infographic maker', url: 'http://www.easel.ly', category: 'infographics_and_data_visualization' },
  { id: 'exhibit', name: 'Exhibit', desc: 'Data publishing framework', url: 'http://www.simile-widgets.org/exhibit', category: 'infographics_and_data_visualization' },
  { id: 'flot', name: 'Flot', desc: 'JavaScript plotting library', url: 'http://www.flotcharts.org', category: 'infographics_and_data_visualization' },
  { id: 'fusioncharts', name: 'FusionCharts', desc: 'Charting suite', url: 'http://www.fusioncharts.com', category: 'infographics_and_data_visualization' },
  { id: 'google-developers-charts', name: 'Google Developers: Charts', desc: 'Chart tools', url: 'https://developers.google.com/chart', category: 'infographics_and_data_visualization' },
  { id: 'graphx', name: 'GraphX', desc: 'Graph processing', url: 'http://spark.apache.org/graphx', category: 'infographics_and_data_visualization' },
  { id: 'highcharts', name: 'Highcharts', desc: 'Interactive charts', url: 'http://www.highcharts.com', category: 'infographics_and_data_visualization' },
  { id: 'hohli', name: 'Hohli', desc: 'Chart builder', url: 'http://charts.hohli.com', category: 'infographics_and_data_visualization' },
  { id: 'infogr-am', name: 'Infogr.am', desc: 'Infographic creator', url: 'https://infogr.am', category: 'infographics_and_data_visualization' },
  { id: 'inkscape', name: 'Inkscape', desc: 'Vector graphics editor', url: 'https://inkscape.org', category: 'infographics_and_data_visualization' },
  { id: 'java-infovis-toolkit', name: 'Java Infovis Toolkit', desc: 'Visualization toolkit', url: 'http://philogb.github.io/jit', category: 'infographics_and_data_visualization' },
  { id: 'jpgraph', name: 'JpGraph', desc: 'PHP graph library', url: 'http://jpgraph.net', category: 'infographics_and_data_visualization' },
  { id: 'jqplot', name: 'jqPlot', desc: 'jQuery plotting plugin', url: 'http://www.jqplot.com', category: 'infographics_and_data_visualization' },
  { id: 'knoema', name: 'Knoema', desc: 'Data visualization platform', url: 'https://knoema.com', category: 'infographics_and_data_visualization' },
  { id: 'leaflet', name: 'Leaflet', desc: 'Interactive maps library', url: 'http://leafletjs.com', category: 'infographics_and_data_visualization' },
  { id: 'linkuroius-viz', name: 'Linkuroius', desc: 'Graph visualization', url: 'http://linkurio.us', category: 'infographics_and_data_visualization' },
  { id: 'listify', name: 'Listify', desc: 'Spreadsheet to listing converter', url: 'http://listify.okfnlabs.org', category: 'infographics_and_data_visualization' },
  { id: 'localfocus', name: 'LocalFocus', desc: 'Data journalism tool', url: 'https://www.localfocus.nl', category: 'infographics_and_data_visualization' },
  { id: 'lucidchart', name: 'Lucidchart', desc: 'Diagramming application', url: 'https://www.lucidchart.com', category: 'infographics_and_data_visualization' },
  { id: 'mapline', name: 'Mapline', desc: 'Mapping tool', url: 'https://mapline.com', category: 'infographics_and_data_visualization' },
  { id: 'nodebox', name: 'Nodebox', desc: 'Generative design tools', url: 'https://www.nodebox.net', category: 'infographics_and_data_visualization' },
  { id: 'observable', name: 'Observable', desc: 'Data app platform', url: 'https://observablehq.com/', category: 'infographics_and_data_visualization' },
  { id: 'openlayers', name: 'OpenLayers', desc: 'Mapping library', url: 'http://openlayers.org', category: 'infographics_and_data_visualization' },
  { id: 'palladio', name: 'Palladio', desc: 'Historical data visualization', url: 'http://hdlab.stanford.edu/palladio', category: 'infographics_and_data_visualization' },
  { id: 'perspective', name: 'Perspective', desc: 'Data visualization component', url: 'https://github.com/finos/perspective', category: 'infographics_and_data_visualization' },
  { id: 'piktochart', name: 'Piktochart', desc: 'Infographic maker', url: 'https://piktochart.com', category: 'infographics_and_data_visualization' },
  { id: 'pixxa', name: 'Pixxa', desc: 'Perspective viewer', url: 'http://www.pixxa.com', category: 'infographics_and_data_visualization' },
  { id: 'plotly', name: 'Plotly', desc: 'Charting library', url: 'https://plot.ly', category: 'infographics_and_data_visualization' },
  { id: 'preceden', name: 'Preceden', desc: 'Timeline maker', url: 'https://www.preceden.com/', category: 'infographics_and_data_visualization' },

  // mac_address_intelligence
  { id: 'ieee-oui-lookup', name: 'IEEE OUI Lookup', desc: 'Official MAC vendor registry', url: 'https://standards.ieee.org/products-services/regauth/oui24/index.html', category: 'mac_address_intelligence' },
  { id: 'macvendors', name: 'MacVendors', desc: 'MAC address vendor lookup', url: 'https://macvendors.com/', category: 'mac_address_intelligence' },

  // metadata_intelligence
  { id: 'exiftool-meta', name: 'ExifTool', desc: 'Read/write file metadata', url: 'https://github.com/exiftool/exiftool', category: 'metadata_intelligence' },
  { id: 'foca', name: 'FOCA', desc: 'Metadata extraction tool', url: 'https://www.elevenpaths.com/labstools/foca/index.html', category: 'metadata_intelligence' },
  { id: 'forensically', name: 'Forensically', desc: 'Image forensics tool', url: 'https://29a.ch/photo-forensics/', category: 'metadata_intelligence' },
  { id: 'metagoofil', name: 'Metagoofil', desc: 'Metadata from documents', url: 'https://code.google.com/archive/p/metagoofil/', category: 'metadata_intelligence' },
  { id: 'metapicz', name: 'Metapicz', desc: 'Online image metadata viewer', url: 'https://metapicz.com/', category: 'metadata_intelligence' },

  // miscellaneous
  { id: 'darksearch-misc', name: 'DarkSearch', desc: 'Dark web search', url: 'https://github.com/itsmehacker/DarkSearch', category: 'miscellaneous' },
  { id: 'filepursuit', name: 'FilePursuit', desc: 'File search engine', url: 'https://filepursuit.com/', category: 'miscellaneous' },
  { id: 'leakix', name: 'LeakIX', desc: 'Exposed assets', url: 'https://leakix.net/', category: 'miscellaneous' },
  { id: 'littlebrother', name: 'LittleBrother', desc: 'Local intelligence gathering', url: 'https://github.com/lulz3xploit/LittleBrother', category: 'miscellaneous' },
  { id: 'netlas', name: 'Netlas', desc: 'Netlas asset search', url: 'https://app.netlas.io/', category: 'miscellaneous' },
  { id: 'osint-combine-tools', name: 'OSINT Combine Tools', desc: 'Tools collection', url: 'https://www.osintcombine.com/tools', category: 'miscellaneous' },
  { id: 'trape', name: 'Trape', desc: 'People tracker on the Internet', url: 'https://github.com/jofpin/trape', category: 'miscellaneous' },
  { id: 'wpscan-misc', name: 'WPSCAN', desc: 'WordPress vulnerability scanner', url: 'https://wpscan.com/', category: 'miscellaneous' },

  // network_intelligence
  { id: 'asnlookup', name: 'ASN Lookup', desc: 'ASN information search', url: 'https://asnlookup.com/', category: 'network_intelligence' },
  { id: 'bgpview', name: 'BGPView', desc: 'ASN & IP intelligence', url: 'https://bgpview.io/', category: 'network_intelligence' },

  // paste_sites
  { id: 'gist', name: 'GitHub Gist', desc: 'Code snippets', url: 'https://gist.github.com/', category: 'paste_sites' },
  { id: 'pastebin', name: 'Pastebin', desc: 'Popular paste site', url: 'https://pastebin.com/', category: 'paste_sites' },
  { id: 'pastesearches', name: 'pastesearches', desc: 'Malicious pastes', url: 'https://hunting.abuse.ch/', category: 'paste_sites' },

  // people_search
  { id: 'beenverified', name: 'BeenVerified', desc: 'People search engine', url: 'https://www.beenverified.com/', category: 'people_search' },
  { id: 'intelius', name: 'Intelius', desc: 'People search service', url: 'https://www.intelius.com/', category: 'people_search' },
  { id: 'pipl', name: 'Pipl', desc: 'People search (paid)', url: 'https://pipl.com/', category: 'people_search' },
  { id: 'spokeo', name: 'Spokeo', desc: 'People search engine', url: 'https://www.spokeo.com/', category: 'people_search' },

  // phone_number_intelligence
  { id: 'numlookup', name: 'NumLookup', desc: 'Phone number lookup', url: 'https://www.numlookup.com/', category: 'phone_number_intelligence' },
  { id: 'numverify', name: 'NumVerify', desc: 'Phone validation API', url: 'https://numverify.com', category: 'phone_number_intelligence' },
  { id: 'phoneinfoga', name: 'PhoneInfoga', desc: 'Phone number OSINT', url: 'https://github.com/sundowndev/phoneinfoga', category: 'phone_number_intelligence' },
  { id: 'truecaller', name: 'Truecaller', desc: 'Caller ID and spam blocking', url: 'https://www.truecaller.com', category: 'phone_number_intelligence' },
  { id: 'truepeoplesearch', name: 'TruePeopleSearch', desc: 'Phone & people lookup', url: 'https://www.truepeoplesearch.com/', category: 'phone_number_intelligence' },

  // privacy_focused_search_engines
  { id: 'disconnect-search', name: 'Disconnect Search', desc: 'Private search proxy', url: 'https://search.disconnect.me/', category: 'privacy_focused_search_engines' },
  { id: 'duckduckgo-privacy', name: 'DuckDuckGo', desc: 'Privacy search', url: 'https://duckduckgo.com/', category: 'privacy_focused_search_engines' },
  { id: 'gibiru-privacy', name: 'Gibiru', desc: 'Uncensored search', url: 'https://gibiru.com/', category: 'privacy_focused_search_engines' },
  { id: 'kagi', name: 'Kagi', desc: 'Premium private search', url: 'https://kagi.com/', category: 'privacy_focused_search_engines' },
  { id: 'mojeek', name: 'Mojeek', desc: 'Independent search engine', url: 'https://www.mojeek.com/', category: 'privacy_focused_search_engines' },
  { id: 'presearch', name: 'Presearch', desc: 'Decentralized search', url: 'https://presearch.org/', category: 'privacy_focused_search_engines' },
  { id: 'qwant', name: 'Qwant', desc: 'Privacy search', url: 'https://www.qwant.com/', category: 'privacy_focused_search_engines' },
  { id: 'search-encrypt', name: 'Search Encrypt', desc: 'Encrypted search', url: 'https://www.searchencrypt.com/', category: 'privacy_focused_search_engines' },
  { id: 'startpage', name: 'Startpage', desc: 'Private search', url: 'https://www.startpage.com/', category: 'privacy_focused_search_engines' },
  { id: 'swisscows', name: 'Swisscows', desc: 'Semantic privacy search', url: 'https://swisscows.com/', category: 'privacy_focused_search_engines' },

  // search_engines
  { id: 'alltheinternet', name: 'AllTheInternet', desc: 'Meta search engine', url: 'http://www.alltheinternet.com', category: 'search_engines' },
  { id: 'aol', name: 'AOL Search', desc: 'Web search', url: 'https://search.aol.com/', category: 'search_engines' },
  { id: 'ask', name: 'Ask', desc: 'Web search', url: 'https://www.ask.com/', category: 'search_engines' },
  { id: 'baidu', name: 'Baidu', desc: 'Chinese search engine', url: 'http://www.baidu.com', category: 'search_engines' },
  { id: 'bing', name: 'Bing', desc: 'Web search', url: 'https://www.bing.com/', category: 'search_engines' },
  { id: 'brave-search', name: 'Brave Search', desc: 'Privacy-first search', url: 'https://search.brave.com/', category: 'search_engines' },
  { id: 'daum', name: 'Daum', desc: 'South Korean search', url: 'https://www.daum.net/', category: 'search_engines' },
  { id: 'eniro', name: 'Eniro', desc: 'Swedish search', url: 'http://www.eniro.se', category: 'search_engines' },
  { id: 'gerdoo', name: 'Gerdoo', desc: 'Iranian search', url: 'http://gerdoo.me', category: 'search_engines' },
  { id: 'ghdb', name: 'Google Hacking Database', desc: 'ExploitDB Dorks', url: 'https://www.exploit-db.com/google-hacking-database', category: 'search_engines' },
  { id: 'goo', name: 'Goo', desc: 'Japanese search', url: 'http://www.goo.ne.jp', category: 'search_engines' },
  { id: 'goodsearch', name: 'Goodsearch', desc: 'Shopping deals search', url: 'https://www.goodsearch.com', category: 'search_engines' },
  { id: 'google-search', name: 'Google Search', desc: 'Web search', url: 'https://www.google.com/', category: 'search_engines' },
  { id: 'impesonal-me', name: 'Impersonal.me', desc: 'Personalized search', url: 'http://www.impersonal.me', category: 'search_engines' },
  { id: 'instya', name: 'Instya', desc: 'Multi-category search', url: 'https://www.instya.com', category: 'search_engines' },
  { id: 'lycos', name: 'Lycos', desc: 'Multimedia search', url: 'https://www.lycos.com', category: 'search_engines' },
  { id: 'najdi', name: 'Najdi', desc: 'Slovenian search', url: 'http://www.najdi.si', category: 'search_engines' },
  { id: 'naver', name: 'Naver', desc: 'South Korean search', url: 'http://www.naver.com', category: 'search_engines' },
  { id: 'onet-pl', name: 'Onet.pl', desc: 'Polish search', url: 'http://www.onet.pl', category: 'search_engines' },
  { id: 'orange', name: 'Orange', desc: 'French search', url: 'http://www.orange.fr', category: 'search_engines' },
  { id: 'parseek', name: 'Parseek', desc: 'Iranian search', url: 'http://www.parseek.com', category: 'search_engines' },
  { id: 'sapo', name: 'SAPO', desc: 'Portuguese search', url: 'http://www.sapo.pt', category: 'search_engines' },
  { id: 'search-ch', name: 'Search.ch', desc: 'Swiss search', url: 'http://www.search.ch', category: 'search_engines' },
  { id: 'search-com', name: 'Search.com', desc: 'Meta search', url: 'https://www.search.com', category: 'search_engines' },
  { id: 'seznam', name: 'Seznam', desc: 'Czech search', url: 'https://seznam.cz', category: 'search_engines' },
  { id: 'sogou', name: 'SoGou', desc: 'Chinese search', url: 'http://www.sogou.com/', category: 'search_engines' },
  { id: 'walla', name: 'Walla', desc: 'Israeli search', url: 'http://www.walla.co.il', category: 'search_engines' },
  { id: 'wolfram-alpha', name: 'Wolfram Alpha', desc: 'Computational search', url: 'https://www.wolframalpha.com/', category: 'search_engines' },
  { id: 'yahoo-search', name: 'Yahoo! Search', desc: 'Web search', url: 'https://search.yahoo.com/', category: 'search_engines' },
  { id: 'yandex', name: 'Yandex', desc: 'Russian search', url: 'http://www.yandex.com', category: 'search_engines' },
  { id: 'you-com', name: 'YOU.com', desc: 'AI-assisted search', url: 'https://you.com/', category: 'search_engines' },
  { id: 'zarebin', name: 'Zarebin', desc: 'Iranian search', url: 'http://zarebin.ir', category: 'search_engines' },

  // social_media_intelligence
  { id: 'hoaxy', name: 'Hoaxy', desc: 'Misinformation tracker', url: 'https://hoaxy.osome.iu.edu/', category: 'social_media_intelligence' },
  { id: 'instaloader', name: 'Instaloader', desc: 'Instagram downloader', url: 'https://github.com/instaloader/instaloader', category: 'social_media_intelligence' },
  { id: 'pushshift', name: 'Pushshift', desc: 'Reddit data provider', url: 'https://search.pushshift.io/', category: 'social_media_intelligence' },
  { id: 'social-analyzer', name: 'Social-Analyzer', desc: 'Social media profiling', url: 'https://github.com/qeeqbox/social-analyzer', category: 'social_media_intelligence' },
  { id: 'social-bearing', name: 'Social Bearing', desc: 'Twitter analytics', url: 'https://socialbearing.com/', category: 'social_media_intelligence' },
  { id: 'social-searcher', name: 'Social Searcher', desc: 'Social media search', url: 'https://www.social-searcher.com/', category: 'social_media_intelligence' },
  { id: 'twint', name: 'Twint', desc: 'Twitter scraping', url: 'https://github.com/twintproject/twint', category: 'social_media_intelligence' },

  // specialty_search_engines
  { id: '2lingual-search', name: '2lingual Search', desc: 'Bilingual search', url: 'http://www.2lingual.com', category: 'specialty_search_engines' },
  { id: 'abusech', name: 'Abusech', desc: 'Threat intelligence search', url: 'https://hunting.abuse.ch', category: 'specialty_search_engines' },
  { id: 'bevigil', name: 'BeVigil', desc: 'Mobile app asset search', url: 'https://bevigil.com/search', category: 'specialty_search_engines' },
  { id: 'bgp-tools', name: 'BGP.tools', desc: 'BGP reconnaissance', url: 'https://bgp.tools', category: 'specialty_search_engines' },
  { id: 'biznar', name: 'Biznar', desc: 'Business search', url: 'http://biznar.com', category: 'specialty_search_engines' },
  { id: 'brightcloud', name: 'BrightCloud', desc: 'URL/IP reputation', url: 'https://brightcloud.com/tools/url-ip-lookup.php', category: 'specialty_search_engines' },
  { id: 'browserleaks', name: 'Browserleaks', desc: 'Browser privacy tests', url: 'https://browserleaks.com/', category: 'specialty_search_engines' },
  { id: 'censys-special', name: 'Censys', desc: 'Internet asset search', url: 'https://search.censys.io/', category: 'specialty_search_engines' },
  { id: 'certkit-certificate-search', name: 'CertKit Certificate Search', desc: 'SSL certificate search', url: 'https://www.certkit.io/tools/ct-logs/', category: 'specialty_search_engines' },
  { id: 'citeseerx', name: 'CiteSeerX', desc: 'Scientific literature search', url: 'http://citeseer.ist.psu.edu', category: 'specialty_search_engines' },
  { id: 'cloudflare-radar', name: 'Cloudflare Radar', desc: 'Internet trends', url: 'https://radar.cloudflare.com', category: 'specialty_search_engines' },
  { id: 'criminal-ip', name: 'Criminal IP', desc: 'Threat intelligence', url: 'https://www.criminalip.io/', category: 'specialty_search_engines' },
  { id: 'crt-sh-special', name: 'crt.sh', desc: 'Certificate transparency search', url: 'https://crt.sh', category: 'specialty_search_engines' },
  { id: 'fofa-special', name: 'FOFA', desc: 'Asset search engine', url: 'https://en.fofa.info/', category: 'specialty_search_engines' },
  { id: 'fullhunt', name: 'FullHunt', desc: 'Attack surface management', url: 'https://fullhunt.io/', category: 'specialty_search_engines' },
  { id: 'google-custom-search', name: 'Google Custom Search', desc: 'Custom search engine', url: 'http://www.google.com/cse', category: 'specialty_search_engines' },
  { id: 'grayhatwarfare-special', name: 'GrayhatWarfare', desc: 'Open buckets search', url: 'https://grayhatwarfare.com/', category: 'specialty_search_engines' },
  { id: 'greynoise-special', name: 'GreyNoise', desc: 'Internet noise intel', url: 'https://www.greynoise.io/', category: 'specialty_search_engines' },
  { id: 'harmari', name: 'Harmari', desc: 'Unified listings search', url: 'https://www.harmari.com/search/unified', category: 'specialty_search_engines' },
  { id: 'hunter-search-engine', name: 'Hunter Search Engine', desc: 'Exposed assets search', url: 'https://hunter.how/', category: 'specialty_search_engines' },
  { id: 'intelligence-x', name: 'Intelligence X', desc: 'Archive & darkweb search', url: 'https://intelx.io/tools', category: 'specialty_search_engines' },
  { id: 'internet-archive-special', name: 'Internet Archive', desc: 'Web archive', url: 'https://archive.org/', category: 'specialty_search_engines' },
  { id: 'islegitsite', name: 'Islegitsite', desc: 'Website trustworthiness check', url: 'https://www.islegitsite.com/', category: 'specialty_search_engines' },
  { id: 'malwarebazaar-special', name: 'MalwareBazaar', desc: 'Malware samples', url: 'https://bazaar.abuse.ch/browse/', category: 'specialty_search_engines' },
  { id: 'mamont', name: 'Mamont', desc: 'Russian search', url: 'https://www.mmnt.ru/', category: 'specialty_search_engines' },
  { id: 'million-short', name: 'Million Short', desc: 'Deep web search', url: 'https://millionshort.com', category: 'specialty_search_engines' },
  { id: 'netlas-io', name: 'Netlas.io', desc: 'Internet asset search', url: 'https://app.netlas.io/', category: 'specialty_search_engines' },
  { id: 'odin', name: 'ODIN', desc: 'Asset and vulnerability search', url: 'https://search.odin.io/', category: 'specialty_search_engines' },
  { id: 'search-abuseipdb', name: 'Search Abuseipdb', desc: 'IP abuse query tool', url: 'https://github.com/oseasfr/search-abuseipdb', category: 'specialty_search_engines' },
  { id: 'shadowserver', name: 'Shadowserver', desc: 'Cyber threat stats', url: 'https://dashboard.shadowserver.org/', category: 'specialty_search_engines' },
  { id: 'shodan-special', name: 'Shodan', desc: 'IoT search engine', url: 'https://www.shodan.io/', category: 'specialty_search_engines' },
  { id: 'wipo', name: 'WIPO', desc: 'Brand database', url: 'https://www3.wipo.int/branddb/en/', category: 'specialty_search_engines' },
  { id: 'worldwidescience-org', name: 'WorldWideScience.org', desc: 'Scientific search', url: 'http://worldwidescience.org', category: 'specialty_search_engines' },
  { id: 'wpscan-special', name: 'Wpscan', desc: 'WordPress security scanner', url: 'https://wpscan.com', category: 'specialty_search_engines' },
  { id: 'yaraify', name: 'YARAif', desc: 'YARA pattern matching', url: 'https://yaraify.abuse.ch/scan/', category: 'specialty_search_engines' },
  { id: 'zanran', name: 'Zanran', desc: 'Data and statistics search', url: 'http://zanran.com', category: 'specialty_search_engines' },
  { id: 'zoomeye-special', name: 'ZoomEye', desc: 'Cyber asset search', url: 'https://www.zoomeye.ai/', category: 'specialty_search_engines' },

  // subdomain_enumeration
  { id: 'amass', name: 'Amass', desc: 'Asset discovery tool', url: 'https://github.com/owasp-amass/amass', category: 'subdomain_enumeration' },
  { id: 'assetfinder', name: 'Assetfinder', desc: 'Find domains and subdomains', url: 'https://github.com/tomnomnom/assetfinder', category: 'subdomain_enumeration' },
  { id: 'chaos', name: 'Chaos', desc: 'Internet-wide asset data', url: 'https://chaos.projectdiscovery.io/', category: 'subdomain_enumeration' },
  { id: 'crt-sh-sub', name: 'crt.sh', desc: 'Certificate transparency', url: 'https://crt.sh', category: 'subdomain_enumeration' },
  { id: 'findomain', name: 'Findomain', desc: 'Cross-platform enumeration', url: 'https://github.com/Findomain/Findomain', category: 'subdomain_enumeration' },
  { id: 'sublist3r', name: 'Sublist3r', desc: 'Subdomain enumeration', url: 'https://github.com/aboul3la/Sublist3r', category: 'subdomain_enumeration' },
  { id: 'subfinder', name: 'Subfinder', desc: 'Fast passive discovery', url: 'https://github.com/projectdiscovery/subfinder', category: 'subdomain_enumeration' },

  // threat_intelligence
  { id: 'alienvault-otx', name: 'AlienVault OTX', desc: 'Threat intel pulses', url: 'https://otx.alienvault.com/', category: 'threat_intelligence' },
  { id: 'any-run', name: 'ANY.RUN', desc: 'Interactive malware sandbox', url: 'https://any.run/', category: 'threat_intelligence' },
  { id: 'apt-groups-and-operations', name: 'APT Groups and Operations', desc: 'Threat actor database', url: 'https://docs.google.com/spreadsheets/u/0/d/1H9_xaxQHpWaa4O_Son4Gx0YOIzlcBWMsdvePFX68EKU/pubhtml?pli=1#', category: 'threat_intelligence' },
  { id: 'aptwiki', name: 'APTWiki', desc: 'Threat actor wiki', url: 'https://apt.threatradar.net/', category: 'threat_intelligence' },
  { id: 'bi-zone', name: 'Bi.Zone', desc: 'Threat groups TTPs', url: 'https://gti.bi.zone/', category: 'threat_intelligence' },
  { id: 'binaryedge-threat', name: 'BinaryEdge', desc: 'Internet attack surface', url: 'https://app.binaryedge.io/', category: 'threat_intelligence' },
  { id: 'breachhq', name: 'BreachHQ', desc: 'Threat actors list', url: 'https://breach-hq.com/threat-actors', category: 'threat_intelligence' },
  { id: 'circl-passive-dns', name: 'CIRCL Passive DNS', desc: 'Passive DNS', url: 'https://www.circl.lu/pdns/', category: 'threat_intelligence' },
  { id: 'cybergeist', name: 'Cybergeist', desc: 'Threat actor profiles', url: 'https://cybergeist.io/threat-actor', category: 'threat_intelligence' },
  { id: 'greynoise-threat', name: 'GreyNoise', desc: 'Internet noise intel', url: 'https://www.greynoise.io/', category: 'threat_intelligence' },
  { id: 'hybrid-analysis-threat', name: 'Hybrid-Analysis', desc: 'Malware analysis', url: 'https://www.hybrid-analysis.com/', category: 'threat_intelligence' },
  { id: 'malwarebazaar-threat', name: 'MalwareBazaar', desc: 'Malware sample database', url: 'https://bazaar.abuse.ch/', category: 'threat_intelligence' },
  { id: 'misp', name: 'MISP', desc: 'Threat sharing platform', url: 'https://www.misp-project.org/', category: 'threat_intelligence' },
  { id: 'riskiq', name: 'RiskIQ / PassiveTotal', desc: 'Passive DNS and risk intel', url: 'https://community.riskiq.com/', category: 'threat_intelligence' },
  { id: 'spyse', name: 'Spyse', desc: 'Cyber asset search', url: 'https://spyse.com/', category: 'threat_intelligence' },
  { id: 'threatcrowd', name: 'ThreatCrowd', desc: 'Threat intelligence', url: 'https://www.threatcrowd.org/', category: 'threat_intelligence' },
  { id: 'threatfox', name: 'ThreatFox', desc: 'Malware IOCs', url: 'https://threatfox.abuse.ch/', category: 'threat_intelligence' },
  { id: 'urlscan', name: 'URLscan', desc: 'Website scanning and screenshots', url: 'https://urlscan.io/', category: 'threat_intelligence' },
  { id: 'virustotal', name: 'VirusTotal', desc: 'File / URL / IP scans', url: 'https://www.virustotal.com/', category: 'threat_intelligence' },
  { id: 'zoomeye-threat', name: 'ZoomEye', desc: 'Internet asset search', url: 'https://www.zoomeye.org/', category: 'threat_intelligence' },

  // username_enumeration
  { id: 'maigret', name: 'Maigret', desc: 'Username search', url: 'https://github.com/soxoj/maigret', category: 'username_enumeration' },
  { id: 'sherlock', name: 'Sherlock', desc: 'Username availability check', url: 'https://github.com/sherlock-project/sherlock', category: 'username_enumeration' },
  { id: 'whatsmyname-user', name: 'WhatsMyName', desc: 'Username enumeration', url: 'https://whatsmyname.app/', category: 'username_enumeration' },

  // vpn_services
  { id: 'offshore-cat', name: 'OffShore.cat', desc: 'Privacy-focused VPN list', url: 'https://offshore.cat/vpn', category: 'vpn_services' },
  { id: 'that-one-privacy-guy', name: 'That One Privacy Guy', desc: 'VPN comparison', url: 'https://thatoneprivacysite.net/', category: 'vpn_services' },
  { id: 'torrentfreak-vpns', name: 'TorrentFreak VPNs', desc: 'Anonymous VPN review', url: 'https://torrentfreak.com/vpn-services-anonymous-review-2017-170304/', category: 'vpn_services' },

  // web_monitoring
  { id: 'alltop', name: 'Alltop', desc: 'News aggregator', url: 'http://alltop.com', category: 'web_monitoring' },
  { id: 'awasu', name: 'Awasu', desc: 'RSS reader', url: 'http://www.awasu.com', category: 'web_monitoring' },
  { id: 'bridge-leslibres', name: 'Bridge.Leslibres', desc: 'RSS bridge', url: 'https://bridge.leslibres.org', category: 'web_monitoring' },
  { id: 'bridge-suumitsu', name: 'Bridge.Suumitsu', desc: 'RSS bridge', url: 'https://bridge.suumitsu.eu', category: 'web_monitoring' },
  { id: 'changedetect', name: 'ChangeDetect', desc: 'Webpage monitoring', url: 'http://www.changedetect.com', category: 'web_monitoring' },
  { id: 'changedetection', name: 'ChangeDetection', desc: 'Page change detection', url: 'http://www.changedetection.com', category: 'web_monitoring' },
  { id: 'changedetection-io', name: 'ChangeDetection.io', desc: 'Open source page monitoring', url: 'https://changedetection.io', category: 'web_monitoring' },
  { id: 'deltafeed', name: 'Deltafeed', desc: 'RSS feed changes', url: 'http://bitreading.com/deltafeed', category: 'web_monitoring' },
  { id: 'diggreader', name: 'DiggReader', desc: 'RSS reader', url: 'http://digg.com/login?next=%2Freader', category: 'web_monitoring' },
  { id: 'feed-exileed', name: 'Feed Exileed', desc: 'RSS feed generator', url: 'http://feed.exileed.com', category: 'web_monitoring' },
  { id: 'feed-filter-maker', name: 'Feed Filter Maker', desc: 'RSS filter', url: 'http://feed.janicek.co', category: 'web_monitoring' },
  { id: 'feedbooster', name: 'FeedBooster', desc: 'RSS enhancer', url: 'http://www.qsensei.com', category: 'web_monitoring' },
  { id: 'feederator', name: 'Feederator', desc: 'RSS aggregator', url: 'http://www.feederator.org', category: 'web_monitoring' },
  { id: 'feedly', name: 'Feedly', desc: 'RSS reader', url: 'http://www.feedly.com', category: 'web_monitoring' },
  { id: 'feedreader', name: 'FeedReader', desc: 'RSS reader', url: 'http://www.feedreader.com', category: 'web_monitoring' },
  { id: 'fetchrss', name: 'FetchRSS', desc: 'RSS generator', url: 'http://fetchrss.com', category: 'web_monitoring' },
  { id: 'flipboard', name: 'Flipboard', desc: 'Social magazine', url: 'http://flipboard.com', category: 'web_monitoring' },
  { id: 'followthatpage', name: 'FollowThatPage', desc: 'Page monitoring', url: 'http://www.followthatpage.com', category: 'web_monitoring' },
  { id: 'google-alerts', name: 'Google Alerts', desc: 'Content change notification', url: 'http://www.google.com/alerts', category: 'web_monitoring' },
  { id: 'infominder', name: 'InfoMinder', desc: 'Web monitoring', url: 'http://www.infominder.com/webminder', category: 'web_monitoring' },
  { id: 'mention', name: 'Mention', desc: 'Real-time monitoring', url: 'https://en.mention.com', category: 'web_monitoring' },
  { id: 'netvibes', name: 'Netvibes', desc: 'Dashboard', url: 'http://www.netvibes.com', category: 'web_monitoring' },
  { id: 'newsblur', name: 'Newsblur', desc: 'RSS reader', url: 'http://newsblur.com', category: 'web_monitoring' },
  { id: 'omeareader', name: 'OmeaReader', desc: 'RSS reader', url: 'http://www.jetbrains.com/omea/reader', category: 'web_monitoring' },
  { id: 'onwebchange', name: 'OnWebChange', desc: 'Web change tracking', url: 'http://onwebchange.com', category: 'web_monitoring' },
  { id: 'reeder', name: 'Reeder', desc: 'RSS reader app', url: 'http://reederapp.com', category: 'web_monitoring' },
  { id: 'rss-bridge', name: 'RSS Bridge', desc: 'RSS feed generator', url: 'https://bridge.suumitsu.eu', category: 'web_monitoring' },
  { id: 'rss-feed-reader', name: 'RSS Feed Reader', desc: 'Chrome extension', url: 'https://chrome.google.com/webstore/detail/rss-feed-reader/pnjaodmkngahhkoihejjehlcdlnohgmp', category: 'web_monitoring' },
  { id: 'rss-micro', name: 'RSS Micro', desc: 'RSS search', url: 'http://www.rssmicro.com', category: 'web_monitoring' },
  { id: 'rss-search-engine', name: 'RSS Search Engine', desc: 'RSS search', url: 'http://ctrlq.org/rss', category: 'web_monitoring' },
  { id: 'rss-search-hub', name: 'RSS Search Hub', desc: 'RSS search', url: 'http://www.rsssearchhub.com', category: 'web_monitoring' },
  { id: 'rssowl', name: 'RSSOwl', desc: 'RSS reader', url: 'http://www.rssowl.org', category: 'web_monitoring' },
  { id: 'selfoss', name: 'Selfoss', desc: 'Self-hosted RSS reader', url: 'http://selfoss.aditu.de', category: 'web_monitoring' },
  { id: 'silobreaker', name: 'Silobreaker', desc: 'Intelligence platform', url: 'http://www.silobreaker.com', category: 'web_monitoring' },
  { id: 'talkwalker', name: 'Talkwalker', desc: 'Social listening', url: 'http://www.talkwalker.com', category: 'web_monitoring' },
  { id: 'the-old-reader', name: 'The Old Reader', desc: 'RSS reader', url: 'http://theoldreader.com', category: 'web_monitoring' },
  { id: 'versionista', name: 'Versionista', desc: 'Website monitoring', url: 'http://versionista.com', category: 'web_monitoring' },
  { id: 'visualping', name: 'Visualping', desc: 'Visual change detection', url: 'https://visualping.io', category: 'web_monitoring' },
  { id: 'webreader', name: 'WebReader', desc: 'RSS reader', url: 'http://www.getwebreader.com', category: 'web_monitoring' },
  { id: 'website-watcher', name: 'WebSite Watcher', desc: 'Page monitoring', url: 'http://www.aignes.com/index.htm', category: 'web_monitoring' },
  { id: 'winds', name: 'Winds', desc: 'RSS reader', url: 'http://winds.getstream.io', category: 'web_monitoring' },
];